services:
  db:
    image: postgres:15
    container_name: bookshop_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookshop_network

  backend:
    build: .
    container_name: bookshop_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - bookshop_network

volumes:
  postgres_data:

networks:
  bookshop_network:
    driver: bridge